apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pds.fullname" . }}
  labels:
    {{- include "pds.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
